name: lint-tidier

on:
  workflow_dispatch:

  pull_request:
    paths:
      - 'include/**/*.h*'
      - 'src/**/*.c*'

jobs:
  lint-tidier-job:
    name: Auto-apply clang-tidy
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/lint-tidier.yml@main
