name: Stress Benchmark

on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'stress_benchmark/**'
      - '.github/workflows/stress_benchmark.yml'
    branches:
      - main

  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'stress_benchmark/**'
      - '.github/workflows/stress_benchmark.yml'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9]+.[0-9]+'

permissions:
  contents: write
  deployments: write


jobs:
  check_actor:
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/check-actor.yml@main
    secrets: inherit

  benchmark:
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/benchmark.yml@main
    with:
      conan_extra_args: "-o \"curaengine/*:enable_benchmarks=True\""
      benchmark_cmd: "stress_benchmark/stress_benchmark -o benchmark_result.json"
      name: "Stress Benchmark"
      output_file_path: "build/Release/benchmark_result.json"
      data_dir: "dev/stress_bench"
      tool: "customSmallerIsBetter"
      alert_threshold: "150%"
      alert_comment_cc_users: "@sfjelstad"
    secrets: inherit
